import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Logout from "./components/logout";
import "./globals.css";
import { AuthProvider } from "./components/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Logout />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
